[custom.all.istream]
type = "local"
path = "/home/rvs314/Code/istream"
ipkg = "istream.ipkg"
test = "test/test.ipkg"

[custom.all.ismk]
type = "local"
path = "."
ipkg = "ismk.ipkg"
test = "test/test.ipkg"

[custom.all.ismk-test]
type = "local"
path = "test"
ipkg = "test.ipkg"